### ISSUE TITLE
DO NOT propose changes in public

### ISSUE THREAD

**Issue by ixti** [keoghpe/alex-slack#1]
Bot should propose changes in private. Otherwise it might be pretty offensive on it's own.
Also it would be pretty nice to have an option to "silent" it on per-user/per-suggestion.

For example, I said something that might be offensive but it's not because of context.
Bot notify me that it's inappropriate in private, probably allowing me to disable further
notifications on that word.

**Comment by keoghpe** [comment]
Hey @ixti, great suggestions. If I have time soon I'll take a look at tackling them or feel free to make a pull request. :smile:

**Comment by onebree** [comment]
Any progress on this issue? I'd like to see it implemented before introducing it to a team I am in.

**Comment by ixti** [comment]
There's a PR #2 for this. So closing issue now.
